@PresentationLayer_HostAddress =  http://localhost:5249

### Get Product By Id
@id=1
GET {{PresentationLayer_HostAddress}}/api/Products/{{id}}

### Get All Types 

GET {{PresentationLayer_HostAddress}}/api/Products/types

### Get ALL Brands 

GET {{PresentationLayer_HostAddress}}/api/Products/brands

###
